=== alex-zuy/boilerplate-generator/processor/src/main/resources/org/alex/zuy/boilerplate/config-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema
        targetNamespace="config-schema.xsd"
        elementFormDefault="qualified"
        xmlns="config-schema.xsd"
        xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="identifierType">
        <xs:restriction base="xs:token">
            <xs:pattern value="[a-zA-Z](\w|\.)*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="identifierTemplateType">
        <xs:restriction base="xs:token"/>
    </xs:simpleType>

    <xs:simpleType name="stringConstantNameStyle">
        <xs:restriction base="xs:token">
            <xs:enumeration value="camelcase"/>
            <xs:enumeration value="uppercase"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="annotationList">
        <xs:sequence>
            <xs:element name="annotation" type="identifierType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="basePackage" type="identifierType"/>

    <xs:element name="supportClasses">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="basePackage" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="metadataClasses">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="propertyClassName" type="identifierTemplateType" minOccurs="0"/>
                <xs:element name="relationshipClassName" type="identifierTemplateType" minOccurs="0"/>
                <xs:element name="stringConstantNameStyle" type="stringConstantNameStyle" minOccurs="0"/>
                <xs:element name="relationshipsClassTerminalMethodNameTemplate" type="identifierTemplateType"
                            minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="generationStyle">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="metadataClasses" maxOccurs="1" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="packageList">
        <xs:sequence>
            <xs:element name="package" type="identifierType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="basePackages" type="packageList"/>

    <xs:element name="typeAnnotations" type="annotationList"/>

    <xs:element name="packageInfoAnnotations" type="annotationList"/>

    <xs:element name="includes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="basePackages" minOccurs="0"/>
                <xs:element ref="typeAnnotations" minOccurs="0"/>
                <xs:element ref="packageInfoAnnotations" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="pattern" type="xs:string"/>

    <xs:complexType name="patternList">
        <xs:sequence>
            <xs:element ref="pattern" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="patterns" type="patternList"/>

    <xs:element name="excludes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="typeAnnotations" minOccurs="0"/>
                <xs:element ref="patterns" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="domain">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="includes"/>
                <xs:element ref="excludes" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="beanProcessing">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="supportClasses"/>
                <xs:element ref="generationStyle"/>
                <xs:element ref="domain"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="configuration">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="beanProcessing"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== alex-zuy/boilerplate-generator/processor/src/test/resources/org/alex/zuy/boilerplate/config/config-minimal.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="config-schema.xsd http://localhost"
        xmlns="config-schema.xsd">
    <beanProcessing>
        <supportClasses>
            <basePackage>com.example.generated.support</basePackage>
        </supportClasses>
        <generationStyle>
        </generationStyle>
        <domain>
            <includes>
                <basePackages>
                    <package>com.example.first</package>
                </basePackages>
            </includes>
        </domain>
    </beanProcessing>
</configuration>

=== alex-zuy/boilerplate-generator/processor/src/test/resources/org/alex/zuy/boilerplate/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="config-schema.xsd"
        xmlns="config-schema.xsd">
    <beanProcessing>
        <generationStyles>
            <style id="main">
                <supportClasses>
                    <basePackage>com.example.generated.support</basePackage>
                </supportClasses>
                <metadataClasses>
                    <basePackage>com.example.generated</basePackage>
                    <propertyClassName>${beanClassName}_p</propertyClassName>
                    <relationshipClassName>${beanClassName}_r</relationshipClassName>
                    <stringConstantNameStyle>camelcase</stringConstantNameStyle>
                </metadataClasses>
            </style>
        </generationStyles>
        <domains>
            <domain style="main">
                <includes>
                    <basePackages>
                        <package>com.example.first</package>
                        <package>com.example.second</package>
                        <package>com.example.third</package>
                    </basePackages>
                    <typeAnnotations>
                        <annotation>com.example.MarkerFirst</annotation>
                        <annotation>com.example.MarkerSecond</annotation>
                    </typeAnnotations>
                    <packageInfoAnnotations>
                        <annotation>com.example.MarkerFirst</annotation>
                        <annotation>com.example.MarkerSecond</annotation>
                    </packageInfoAnnotations>
                </includes>
                <excludes>
                    <typeAnnotations>
                        <annotation>com.example.ExcludeMarkerFirst</annotation>
                        <annotation>com.example.ExcludeMarkerSecond</annotation>
                    </typeAnnotations>
                    <patterns>
                        <pattern>regex to exclude classes by FQN</pattern>
                        <pattern>regex to exclude classes by FQN</pattern>
                    </patterns>
                </excludes>
            </domain>
        </domains>
    </beanProcessing>
</configuration>

=== alex-zuy/boilerplate-generator/processor-it/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="config-schema.xsd"
        xmlns="config-schema.xsd">
    <beanProcessing>
        <supportClasses>
            <basePackage>org.alex.zuy.boilerplate.test.generated.support</basePackage>
        </supportClasses>
        <generationStyle>
                <metadataClasses>
                    <propertyClassName>${beanClassName}Properties</propertyClassName>
                    <relationshipClassName>${beanClassName}Relationships</relationshipClassName>
                    <stringConstantNameStyle>uppercase</stringConstantNameStyle>
                    <relationshipsClassTerminalMethodNameTemplate>${beanPropertyName}Property</relationshipsClassTerminalMethodNameTemplate>
                </metadataClasses>
        </generationStyle>
        <domain>
            <includes>
                <typeAnnotations>
                    <annotation>org.alex.zuy.boilerplate.test.IncludeMarker</annotation>
                </typeAnnotations>
            </includes>
        </domain>
    </beanProcessing>
</configuration>
